version: '3.7'

services:
  restaurant-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    container_name: restaurant-reviews-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  restaurant-reviews-db-volume:
