version: '3.7'

services:
  db:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    container_name: restaurant-delivery-db
    volumes:
      - ./db:/var/lib/postgresql/restaurant-delivery-data
    env_file:
      - .env

volumes:
  db:

